name: flow_mate
description: "A personal Flutter money tracker app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Hive for offline storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7   # For generating unique IDs
  intl: ^0.18.1  # For date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Hive generator & build runner
  hive_generator: ^2.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
